use_frameworks!

platform :ios, '12.4'

target 'Apple-Cocoapod-KochavaEntitlements_Example' do
  pod 'Apple-Cocoapod-KochavaEntitlements', :path => '../'

  target 'Apple-Cocoapod-KochavaEntitlements_Tests' do
    inherit! :search_paths

    
  end
end
